### PR TITLE
Change the user from  to  and corresponding password too.

### PR DESCRIPTION
**Pull request by spattk**
It helps in working on multiple projects simultaneously.
A new user can be created and given the respective permissions to access the database.

### CODE REVIEW

**Comment by ankita132** [comment]
@siteshpattanaik001 pull request should always be sent from your local branches and not master branch.And I dont really understand the use of setting a password and a new username for this project.

**Comment by spattk** [comment]
Because when one is involved with multiple projects and each use same root@localhost as username but different password that creates inconsistencies for the contributer. 
And this was a simple change so i didn't make any branch and directly committed.

**Comment by ankita132** [comment]
well for different projects we have different databases to work on.Also you are not wrong in your case either.Nonetheless you should send a PR from local branches for getting the PR merged.

**Comment by spattk** [comment]
Ok would do that. :relaxed:

**Pull request closed without merging**
