### PR TITLE
date format fixed

### PR DESCRIPTION
**Pull request by Shashwat-Garg**
Wrong date was getting saved. Date format corrected.
Solution to Issue #11
As well as the problem of special characters in First name, second name, UserName, Password, and Email is also resolved.

### CODE REVIEW

**Comment by ankita132** [comment]
@Shashwat-Garg  did you run the app before sending a pr?Its giving error right now for registration

**Comment by Shashwat-Garg** [comment]
Yup I ran it and it went perfectly fine.
I'll once again see to it.

**Comment by Shashwat-Garg** [comment]
what exactly is the problem in profile.php ?

**Comment by Shashwat-Garg** [comment]
I'm sorry.
Looks like there was a problem with the backticks (`) I was using.
It worked for me in the beginning though.

**Comment by ankita132** [comment]
thats nice.
fixes #11

**Pull request merged**
