### PR TITLE
Notes_app with calendar & event scheduler.

### PR DESCRIPTION
**Pull request by theheedfulcoder**
I have just tried to add an important feature with which notes app will get its functionality more vulnerable to use i.e. Calendar(Date picker) & Reminder for the event scheduler, also did I add a notification link at top right side as it can be helpful for later use. **This change is only added to the add.php for to check whether I can add it to rest of the pages like edit.php,remove.php, etc. one by one.**Please say shall I proceed @ankita132 with this.

### CODE REVIEW

**Comment by ankita132** [comment]
i am not able to understand the relevance of time scheduler in our app.

**Comment by ankita132** [comment]
also i guess you are using github for sending a pr.I suggest if you are using windows please download git bash and send prs.It would be very helpful for you.

**Comment by theheedfulcoder** [comment]
The Date can be really helpful at times when the user want himself to be notified with a particular note at that date. It actually works like an reminder for a particularly committed task to do that the user noted it from before hand.

**Comment by ankita132** [comment]
@dipayan6ghosh  it has merge conflicts.Can you just resolving them?

**Comment by theheedfulcoder** [comment]
Ok. I have resolved it and have send another PR. And I am closing this one. @ankita132

**Pull request closed without merging**
