### PR TITLE
Merge pull request #3 from ankita132/master

### PR DESCRIPTION
**Pull request by theheedfulcoder**
Update from original.

### CODE REVIEW

**Comment by theheedfulcoder** [comment]
userinfo.sql and notes.sql can be moved inside the model folder.

**Comment by ankita132** [comment]
did you not delete the other files in the repo?

**Comment by ankita132** [comment]
commendable job on MVC by the way @dipayan6ghosh .Also change the input type of password as password its still text

**Comment by theheedfulcoder** [comment]
no, haven't deleted until it's final.
Thankyou :)
Yes, I have changed the input type of password's in various php pages.

**Comment by ankita132** [comment]
I could have accepted your PRs but I won't because this is not a good practice to make small changes in different branches and send several PRs.You could have just made changes to your branch and then pushed, it would have shown the commits here.No need to send separate PRs then.Also don't send PRs from the master branch.

**Comment by ankita132** [comment]
this can be closed i guess?

**Comment by theheedfulcoder** [comment]
As you find better. :)

**Comment by ankita132** [comment]
i mean does this do something new ? i guess everything has been covered in the old PR.

**Pull request closed without merging**
