### PR TITLE
"Change Profile Image" functionality added

### PR DESCRIPTION
**Pull request by prabhakarpd7284**
Issue #26 fixed.
Modified **profile.php** and added **upload.php**.
User can update image by clicking on image itself.

### CODE REVIEW

**Comment by ankita132** [comment]
@prabhakarpd7284  nice work.Can you just add a field to upload the profile image in the view.php

**Comment by prabhakarpd7284** [comment]
Made required changes in **view.php** and **upload.php**.
User can select a profile image during signup process also.

**Comment by ankita132** [comment]
image

**Comment by ankita132** [comment]
moreover i was able to create an account even if i did not upload my image.

**Comment by prabhakarpd7284** [comment]
It was working fine with xampp on windows 10, but still I'm gonna look into it.
And I don't think profile image uploading should be compulsory during signup process. But if you want it, then I will also do so.

**Comment by prabhakarpd7284** [comment]
Issue in above image has been taken care of.
Actually I had forget to implement **Existing Directory Check**.

**Comment by prabhakarpd7284** [comment]
Should image upload be compulsary for sign up?

**Comment by ankita132** [comment]
it works for me now

**Comment by ankita132** [comment]
its okay if we dont make it compulsory but i guess i am not able to upload picture while signup. The image upload upload in the profile.php seems perfectly fine

**Comment by prabhakarpd7284** [comment]
You have to click on **No file chosen**  next to Choose file button.

**Comment by ankita132** [comment]
working fine. Nice work @prabhakarpd7284 .

**Pull request merged**
